sudo: required
services:
  - docker

before_install:
  - docker build -t jonathanjia/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jonathanjia/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-330905704762
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS-ACCESS-KEY
  secret_access_key:
    secure: $AWS-SECRET-ACCESS-KEY
