sudo: required
services:
  - docker

before_install:
  - docker build -t jonathanjia/docker-react -f Dockerfile.dev .

script:
  - docker run jonathanjia/docker-react npm run test -- --coverage